
version: 2.1

jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
  
workflows:
  build-workflow:
     jobs:
      - build:
          context: SonarCloud