
version: 2.1

orbs: 
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
      - run: npm install
      - run: npm test


workflows:
  build-workflow:
      jobs:
        - build
        context: sonarcloud