
version: 2.1



jobs:
  build:
    docker:
      - image: cimg/node:12.22.9
    steps:
      - checkout
      - run: npm install
      - run: npm run coverage


workflows:
  build-workflow:
      jobs:
        - build